### ISSUE TITLE
strange behavior of projectiles

### ISSUE THREAD

**Issue by xhelp00** [xhelp00/cub3d#16] opened 2023-10-16 10:04 UTC
![image](https://github.com/xhelp00/cub3d/assets/111277585/75640f8f-ce04-4005-9790-722bd5ec674a)
when you try to shoot enemy sometimes it happens that hit is not handled correctly and projectile stay there hanging...

**Comment by AntessTerra** [comment] 2023-10-16 11:36
Caused by bad merge on dev-petr branch, fixed now

**Closed by AntessTerra** 2023-10-16 11:36 UTC
